version: '3.1'

services:
  app:
    build: .
    environment:
      - DB_URL=jdbc:postgresql://db/$DB_USER
      - DB_USER
      - DB_PASS
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - ./db/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS

volumes:
  data:
